### ISSUE TITLE
Slate's note about tagging places you've been triggers every loop

### ISSUE THREAD

**Issue by aaronhowser1** [xen-42/ow-decloaked#1]
I assume this was for the trailer (which is very good) but it's a bit annoying having to go through the conversation every single loop

**Comment by xen-42** [comment]
Sorry that I didn't see this until now. I'm pretty sure this is a vanilla bug. Will check though.

**Comment by aaronhowser1** [comment]
Removing the mod fixes it, adding it back causes it again

**Comment by xen-42** [comment]
Oh yeah would you look at that, thanks for bringing it to my attention. It seems that entering the cloaking field without targetting the Stranger resets Slate's dialogue condition, and my mod ends up triggering that same reset. I've just made it so Slate never says the lines if the mod is installed bc it doesn't make sense since the Stranger is right there lol. Thanks again!

**Comment by aaronhowser1** [comment]
Awesome, glad I could help!
