### ISSUE TITLE
Lost ship & scout markers

### ISSUE THREAD

**Issue by TrottyMan** [xen-42/ow-decloaked#3]
Seems when this is installed I lose the HUD marker for the Scout & the ship.
Not the biggest problem but cause some confusion in Dark Bramble.

My mods are:
New Horizons
Menu Framework
Vanilla Fix
Common Camera Utility
Scout Streaming
Ship Log Slide Reel Player Plus
Custom Ship Log Modes
Visible Stranger

**Comment by Tizitendo** [comment]
Same problem. It happens when I have this mod plus New Horizons installed

**Comment by xen-42** [comment]
Will be fixed in the next release of New Horizons

Basically the game checks if the player is in the cloak, and if the ship/probe is in the cloak, and if they both had the same value (both inside or both outside) itd show or hide the marker. For some reason with the cloak destroyed NH would just default to false instead of true there. Silly.
